{"name": "test_invalid_credentials[chrome]", "status": "passed", "description": "Test case for invalid Login credentials.", "attachments": [{"name": "stdout", "source": "d2aed6b4-5637-48cb-a7df-1add8e19b5bb-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "driver_setup", "value": "'chrome'"}], "start": 1745668624320, "stop": 1745668642943, "uuid": "79efb09f-7210-45a7-930d-196f8cd28fbb", "historyId": "67c145a7e43afdba2e3334c34efeb921", "testCaseId": "ef7373e7d568430ffce9b3d52770a421", "fullName": "tests.test_login.TestLogin#test_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('driver_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-EQTA2OP"}, {"name": "thread", "value": "5676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}